updated robertson docs
ComputationalScienceLaboratory/ODE-Test-Problems pull request #106
Opened 2023-07-10 21:14 UTC by elswit

2023-07-17 02:09 UTC, Steven-Roberts requested changes

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/+presets/Canonical.m
> +    % The classic problem with the classic coeeficients $K_1 = 4e-2, K2 = 3e7, K3 = 1e4$.
Mention this preset is referred to as ROBER in Solving ODEs II pg 144.

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonProblem.m
> +    % The Robertson Problem is  a simple, stiff chemical reaction that
Need a one line summary before the description

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonProblem.m
> +    % \begin{align*}
I don't think align is needed

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonProblem.m
> +    % | Stiff               | yes                     |
yes -> typically, depending on $K_1$, $K_2$, and $K_3$.

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonProblem.m
> +    %
Remove empty line

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonProblem.m
> +    %
remove empty line

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonParameters.m
> +        % Reaction rate $K_1$
```suggestion
        % The reaction rate $K_1$
```

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonParameters.m
> +        % Reaction rate $K_2$
```suggestion
        % The reaction rate $K_2$
```

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonParameters.m
> +        % Reaction rate $K_3$
```suggestion
        % The reaction rate $K_3$
```

2023-07-17 02:09 UTC, Steven-Roberts commented on toolbox/+otp/+robertson/RobertsonProblem.m
> +    end
```suggestion
end
```

2023-07-20 17:09 UTC, elswit commented on toolbox/+otp/+robertson/RobertsonProblem.m
> +    % \begin{align*}
It's tider when $K$s are aligned

2023-08-23 01:56 UTC, elswit reviewed
fixed md table miss align

2023-08-23 02:09 UTC, merged