Lorenz 63 docs
ComputationalScienceLaboratory/ODE-Test-Problems pull request #108
Opened 2023-07-18 16:16 UTC by AndreyAPopov

This is still a work in progress

2023-07-26 02:23 UTC, Steven-Roberts requested changes
Some edits on first review. I still need to view it locally for final review

2023-07-26 02:23 UTC, Steven-Roberts commented on docs/references.bib
> +  publisher={CRC press}
Include doi, eddition, and ISBN: [10.1201/9780429492563](https://doi.org/10.1201/9780429492563)

2023-07-26 02:23 UTC, Steven-Roberts commented on docs/references.bib
> +  title={Nonlinear dynamics and chaos with student solutions manual: With applications to physics, biology, chemistry, and engineering},
```suggestion
  title={Nonlinear Dynamics and Chaos: {W}ith applications to physics, biology, chemistry, and engineering},
```

2023-07-26 02:23 UTC, Steven-Roberts commented on docs/references.bib
> +  year={1963}
Include doi: [https://doi.org/10.1175/1520-0469(1963)020<0130:DNF>2.0.CO;2](https://doi.org/10.1175/1520-0469(1963)020%3C0130:DNF%3E2.0.CO;2)

2023-07-26 02:23 UTC, Steven-Roberts commented on toolbox/+otp/+lorenz63/Lorenz63Problem.m
> +    % | Chaotic             | typically, depending on parameters      |
Let's leave chaotic out of the table notes. We can mention it elsewhere.

2023-07-26 02:23 UTC, Steven-Roberts commented on toolbox/+otp/+lorenz63/Lorenz63Problem.m
> +    % | Stiff               | no                                      |
not typically, depending on $\sigma$, $\rho$, and $\beta$.

2023-08-23 02:35 UTC, merged

2023-08-23 02:35 UTC, elswit commented on toolbox/+otp/+lorenz63/Lorenz63Problem.m
> +    % :doc:`Lorenz '96 Problem </problems/Lorenz96Problem>`
@elswit This is useful