Add tests for plot and movie
ComputationalScienceLaboratory/ODE-Test-Problems pull request #82
Opened 2023-05-20 17:43 UTC by AndreyAPopov

2023-06-08 04:27 UTC, Steven-Roberts commented
I'm ok with merging this (maybe after #95). I haven't reviewed carefully, but I'll go though all the tests together carefully in the future

2023-06-23 23:31 UTC, elswit commented
Added  fix for #91

2023-07-07 02:35 UTC, Steven-Roberts requested changes

2023-07-07 02:35 UTC, Steven-Roberts commented on tests/+problemtests/validateqg.m
> +    % if it failed to build, other tests would show it.
I think the try catch is unnecessary for this reason

2023-07-07 02:35 UTC, Steven-Roberts commented on tests/validateallderivatives.m
>          continue;
Probably don't need try catch

2023-07-07 02:35 UTC, Steven-Roberts commented on tests/validateallplots.m
> +        continue;
Same as above

2023-07-07 02:35 UTC, Steven-Roberts commented on tests/validateallplots.m
> +    if problem.NumVars > 1
It still works with 1 var

2023-07-07 02:35 UTC, Steven-Roberts commented on tests/validateallplots.m
> +        problem.plot(sol);
```
fig = problem.plot(sol);
close(fig)
```

2023-07-26 00:59 UTC, AndreyAPopov commented on tests/validateallplots.m
> +    if problem.NumVars > 1
It doesn't work for me.

2023-10-11 01:47 UTC, Steven-Roberts commented
Add option to test plots but not movies in Octave. We can test what will happen on GitHub by running Octave without graphics

2023-10-11 01:48 UTC, Steven-Roberts commented
TODO: fix formatting of PASS in table for some problems

2023-11-29 02:35 UTC, AndreyAPopov commented
I think this one is ready

2024-01-17 02:59 UTC, merged