Feature/gifs
ComputationalScienceLaboratory/ODE-Test-Problems pull request #93
Opened 2023-06-05 02:56 UTC by elswit

added script that lists all test problems and creates movies for them

2023-06-08 04:22 UTC, Steven-Roberts requested changes
This very general functionality fits well with the movie tests in #82 btw.

Here's another idea: what if we generate a movie for all problems (or presets) and include it in the sphinx docs. That would look cool online.

2023-06-08 04:22 UTC, Steven-Roberts commented on gallery/makeMovie.m
> +if ~ isfolder('animations')
This check isn't needed. `mkdir` doesn't throw an error if it already exists

2023-06-08 04:22 UTC, Steven-Roberts commented on gallery/makeMovie.m
> +    eval(strcat(['problem =', listAllExperiments{indx}]));
`problem = eval(listAllExperiments{indx})`

2023-06-08 04:22 UTC, Steven-Roberts commented on gallery/makeMovie.m
> +end
listAllExperiments = {preset.presetclass};

2023-06-08 04:22 UTC, Steven-Roberts commented on gallery/makeMovie.m
> +            args     = strcat(['-i ' ...
No need to call `strcat` if you have square brackets

2023-06-08 04:22 UTC, Steven-Roberts commented on gallery/makeMovie.m
> +        definput = {'/opt/homebrew/bin/ffmpeg'};
I suggest making this file a function with this an an argument. By default this can be `ffmpeg` which assumes it's in the path

2023-06-26 19:33 UTC, elswit commented
I've updated the script, basically getting rid of all the gui since we will only use the animation script internally.

2023-07-09 21:57 UTC, elswit reviewed
Moved the plotting script to `images` subdirectory to avoid cluttering

2024-09-27 02:03 UTC, closed without merging